name: Build and Release Binaries

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            extension: ""
          - os: macos-latest
            target: x86_64-apple-darwin
            extension: ""
          - os: macos-latest
            target: aarch64-apple-darwin
            extension: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            extension: ".exe"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry
          restore-keys: |
            ${{ runner.os }}-cargo-registry

      - name: Cache Cargo index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/index
          key: ${{ runner.os }}-cargo-index
          restore-keys: |
            ${{ runner.os }}-cargo-index

      - name: Cache Cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ matrix.target }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-${{ matrix.target }}

      - name: Build the project
        run: cargo build --release --target ${{ matrix.target }}

      - name: Create artifact directory
        run: mkdir -p artifacts

      - name: Copy binary to artifacts
        run: cp target/${{ matrix.target }}/release/famli3${{ matrix.extension }} artifacts/famli3-${{ github.ref_name }}-${{ matrix.os }}${{ matrix.extension }}

      - name: Upload release assets
        uses: actions/upload-artifact@v3
        with:
          name: famli3-${{ github.ref_name }}-${{ matrix.os }}${{ matrix.extension }}
          path: artifacts/famli3-${{ github.ref_name }}-${{ matrix.os }}${{ matrix.extension }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: famli3-${{ github.ref_name }}-${{ matrix.os }}${{ matrix.extension }}
          path: artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/famli3-${{ github.ref_name }}-${{ matrix.os }}${{ matrix.extension }}
          asset_name: famli3-${{ github.ref_name }}-${{ matrix.os }}${{ matrix.extension }}
          asset_content_type: application/octet-stream
